stages:
  - build-kaniko
  - test
  # - deploy

build-hotel-api-job:
  stage: build-kaniko

  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/api"
      --dockerfile "${CI_PROJECT_DIR}/api/Dockerfile"
      --build-arg SOURCEFOLDER=hotel
      --target test
      --destination "registry.example.local/hotel-api-test:${CI_COMMIT_SHORT_SHA}"
      --verbosity=info
      --insecure-registry registry.example.local
      --skip-tls-verify-registry registry.example.local
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/api"
      --dockerfile "${CI_PROJECT_DIR}/api/Dockerfile"
      --build-arg SOURCEFOLDER=hotel
      --target final
      --destination "registry.example.local/hotel-api:dev"
      --verbosity=info
      --insecure-registry registry.example.local
      --skip-tls-verify-registry registry.example.local
      # --destination "registry.example.local/hotel-api:${CI_COMMIT_TAG}"
  # rules:
  #   - if: $CI_COMMIT_TAG

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - sleep 15
    - echo "Code coverage is 90%"

lint-test-job:
  stage: test
  script:
    - echo "Linting code... This will take about 10 seconds. "
    - sleep 10
    - echo "No lint issues found."

# deploy-job:
#   stage: deploy
#   script:
#     - echo "Deploying application..."
#     - echo "Application successfully deployed."