---
# tasks file for roles/upgrade-to-bullseye
# 1 - Backup the system.

# 2 - Update existing packages and reboot the Debian 9 system.

- name: Update all packages to their latest version
  apt:
    update_cache: yes

- name: Upgrade all packages to their latest version
  apt:
    name: "*"
    state: latest

# 3 - Edit the file /etc/apt/sources.list using a text editor and replace each instance of 'bullseye' with 'bullseye'.

# 4 - Next find the security line, replace keyword 'bullseye/updates' with 'bullseye-security'.
# ```
# deb http://deb.debian.org/debian/ bullseye main
# deb http://deb.debian.org/debian/ bullseye-updates main
# deb http://security.debian.org/debian-security bullseye-security main
# ```

- name: Template a file to /etc/apt/sources.list
  template:
    src: "bullseye_sources.list"
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: "0644"

# 5 - Update the packages index on Debian Linux, run:
#     `sudo apt update`

- name: Update all packages to their latest version
  apt:
    update_cache: yes

#6 - Prepare for the operating system upgrade, run:
#    `sudo apt upgrade`

- name: Upgrade all packages to their latest version
  apt:
    name: "*"
    state: latest

# 7 - Finally, update Debian 10 to Debian 11 by running:
#    `sudo apt full-upgrade`

- name: Upgrade to Debian 11 (apt-get dist-upgrade)
  apt:
    upgrade: full

# 8 - Reboot the Linux system so that you can boot into Debian 10

- name: restart server
  shell: 'sleep 1 && shutdown -r now "Reboot triggered by Ansible" && sleep 1'
  async: 1
  poll: 0
  become: true
