---
# handlers file for roles/kubernetes

- name: reload containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted


- name: enable kubelet service
  service:
    name: kubelet
    enabled: yes

- name: Restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted

- name: wait for kubeapi server
  uri:
    url: "https://{{ kubernetes_vip_ip }}:{{ kubernetes_api_port }}/healthz"
    status_code: 200
    validate_certs: no
  register: result
  until: result.status == 200
  retries: 90
  delay: 15
  listen: "wait kube-vip"