---
# handlers file for roles/kubernetes

- name: Start containerd
  ansible.builtin.systemd:
    name: containerd
    state: started
    enabled: yes
    daemon_reload: yes


- name: enable kubelet service
  service:
    name: kubelet
    enabled: yes
    daemon_reload: yes
    state: restarted

# - name: Restart kubelet
#   service:
#     name: kubelet
#     daemon_reload: yes
#     state: restarted
#     enabled: yes

