---

- name: Check if /var/lib/kubelet directory exist
  ansible.builtin.stat:
    path: /var/lib/kubelet
  register: kubelet_dir

# - set_fact:
#     kubernetes_ip_address: "{{ item }}"
#   when: "item | ipaddr( kubernetes_subnet )"
#   with_items: "{{ ansible_all_ipv4_addresses | difference([kubernetes_vip_ip]) }}"

# - set_fact:
#     api_server_endpoint: "{% if groups['kubemaster'] | length > 1 %}{{ kubernetes_vip_ip }}{% else %}{{ hostvars[groups['kubemaster'][0]]['kubernetes_ip_address'] }}{% endif %}"

# - name: "wait for kubeapi server"
#   uri:
#     url: "https://{{ api_server_endpoint }}:{{ kubernetes_api_port }}/healthz"
#     status_code: 200
#     validate_certs: no
#   register: result
#   until: result.status == 200
#   retries: 90
#   delay: 15

