---

- name: Check if /var/lib/kubelet directory exist
  ansible.builtin.stat:
    path: /var/lib/kubelet
  register: kubelet_dir

- set_fact:
    api_server_endpoint: 172.16.228.15

- name: "wait for kubeapi server"
  uri:
    url: "https://{{ api_server_endpoint }}:{{ kubernetes_api_port }}/healthz"
    status_code: 200
    validate_certs: no
  register: result
  until: result.status == 200
  retries: 90
  delay: 15

