---
# tasks file for roles/kubernetes

- include_tasks: 
    file: "setup-repo-debian.yml"
    apply:
      tags: repo
  tags: repo

- setup:

- include_tasks: 
    file: preflight.yml
    apply:
      tags: preflight
  tags: preflight

- include_tasks: 
    file: cri-install.yml
    apply:
      tags: cri
  tags: cri

- include_tasks: 
    file: kubectl-install.yml
    apply:
      tags: kubectl
  tags: kubectl

- include_tasks: 
    file: helm-install.yml
    apply:
      tags: helm
  tags: helm
  when:
    - inventory_hostname in groups['kubemaster']

- include_tasks: 
    file: init-cluster.yml
    apply:
      tags: kubeinit
  tags: kubeinit
  when:
    - inventory_hostname in groups['kubemaster']


- include_tasks: 
    file: join-cluster.yml
    apply:
      tags: kubejoin
  tags: kubejoin
  when:
    - inventory_hostname in groups['kubeworkers']

- debug:
    msg: "{{ kubernetes_init }}"

- include_tasks: 
    file: post-join-cluster.yml
    apply:
      tags: postkubejoininit
  tags: postkubejoininit
  when:
    - inventory_hostname in groups['kubemaster']
    # - kubernetes_init
