---

- name: Install required system packages
  ansible.builtin.apt: 
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: yes 
    force_apt_get: yes


- name: Create apt Key directory
  ansible.builtin.file: 
    name: /etc/apt/keyrings
    state: directory

- name: Add Google GPG apt Key
  ansible.builtin.get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /etc/apt/keyrings/kubernetes-archive-keyring.gpg

- name: Add K8s Repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
  ignore_errors: "{{ ansible_check_mode }}"

- name: Apt update
  ansible.builtin.apt:
    update_cache: true


