
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "kapacitor-vol.fullname" . }}
  labels:
    {{- include "kapacitor-vol.labels" . | nindent 4 }}
spec:
  storageClassName: {{ include "kapacitor-vol.fullname" . }}
  capacity:
    storage: {{ .Values.pv.capacity.storage }}
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: {{ .Values.pv.hostPath.path }}

  
  # accessModes:
  # - ReadWriteOnce
  # hostPath:
  #   path: /tmp/repository