apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-registry.fullname" . }}
  labels:
    {{- include "my-registry.labels" . | nindent 4 }}
data:
  config.yml: |
      version: 0.1
      log:
        fields:
          service: registry
      storage:
        cache:
          blobdescriptor: inmemory
        filesystem:
          rootdirectory: /var/lib/registry
      http:
        addr: :5000
        secret: changeme
        tls:
          certificate: /certs/tls.crt
          key: /certs/tls.key
        headers:
          X-Content-Type-Options: [nosniff]
      health:
        storagedriver:
          enabled: true
          interval: 10s
          threshold: 3