apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-registry.fullname" . }}
  labels:
    {{- include "my-registry.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "my-registry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "my-registry.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "my-registry.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: repo-vol
              mountPath: "/var/lib/registry"
            # - name: certs-ca-vol
            #   mountPath: "/certs"
            #   readOnly: true
            # - name: config-vol
            #   mountPath: "/etc/docker/registry"
            #   readOnly: true
            # - name: auth-vol
            #   mountPath: "/auth"
            #   readOnly: true
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: repo-vol
          persistentVolumeClaim:
            claimName: {{ include "my-registry.fullname" . }}
        # - name: certs-ca-vol
        #   secret:
        #     secretName: tls-registry-secret
        # - name: config-vol
        #   configMap:
        #     name: {{ include "my-registry.fullname" . }}
        # - name: auth-vol
        #   secret:
        #     secretName: auth-secret
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
