apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "my-registry.fullname" . }}-pv
  labels:
    {{- include "my-registry.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /tmp/repository