
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "my-registry.fullname" . }}
  labels:
    {{- include "my-registry.labels" . | nindent 4 }}
spec:
  storageClassName: {{ include "my-registry.fullname" . }}-manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/data/nfs/my-registry"

  
  # accessModes:
  # - ReadWriteOnce
  # hostPath:
  #   path: /tmp/repository