apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "my-registry.fullname" . }}-pvc
  labels:
    {{- include "my-registry.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi