---

- name: install nfs-utils
  ansible.builtin.apt:
    name: nfs-common
    state: present
    update_cache: yes


- name: Create a mountable directory if it does not exist
  file:
    path: /data/nfs
    state: directory
    owner: root
    group: root
    mode: '0775'

- name: Mount volumn
  shell: mount "{{ groups['nfs_server'][0] }}":/data/nfs /data/nfs

- name: Make sure line is in /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    state: present
    regexp: "^{{ groups['nfs_server'][0] }}:/data/nfs /data/nfs nfs auto,nofail,noatime,nolock,intr,tcp,actimeo=1800 0 0$"
    line: "{{ groups['nfs_server'][0] }}:/data/nfs /data/nfs nfs auto,nofail,noatime,nolock,intr,tcp,actimeo=1800 0 0"