---

# - hosts: gitlab
#   become: yes
#   roles: 
#     - roles/gitlab
#   vars_files:
#     - vars.yaml


# - hosts: kubernetes
#   become: yes
#   roles: 
#     - roles/kubernetes
#   vars_files:
#     - vars.yaml

# - hosts: kubernetes
#   become: yes
#   roles: 
#     - roles/raw_nfs
#   vars_files:
#     - vars.yaml

# - hosts: kubernetes
#   become: yes
#   roles: 
#     - roles/docker_registry
#   vars_files:
#     - vars.yaml

# - hosts: kubernetes
#   become: yes
#   roles: 
#     - roles/kube_gitlab_runner
#   vars_files:
#     - vars.yaml

- hosts: kubernetes
  become: yes
  roles: 
    - roles/kube_tickstack
  vars_files:
    - vars.yaml

