---

# - hosts: kubernetes
#   become: yes
#   roles: 
#     - roles/kubernetes
#   vars_files:
#     - vars.yaml

- hosts: gitlab
  become: yes
  roles: 
    - roles/gitlab
  vars_files:
    - vars.yaml