---

- hosts: kubemaster
  become: yes
  roles: 
    - roles/kubernetes
  vars_files:
    - vars.yaml

- hosts: kubeworker 
  become: yes
  roles: 
    - roles/kubernetes
  vars_files:
    - vars.yaml