---

- hosts: kubemaster
  become: yes
  roles: 
    - roles/kubernetes
  vars:
    - k8s_node_role: master
  vars_files:
    - vars.yaml

- hosts: kubeworkers 
  become: yes
  roles: 
    - roles/kubernetes
  vars:
    - k8s_node_role: worker
  vars_files:
    - vars.yaml